const helpers = require('yeoman-test')
const assert = require('yeoman-assert')
const path = require('path')

describe('branded-go-service:server', function() {
    beforeEach(function() {
        return helpers.run(path.join(__dirname, '../generators/server'))
        .withPrompts({name: 'some-service'})
    })

    it('generates a project', function() {
        assert.file('certs/test/Makefile')
        assert.file('protocol/hello.pb.go')
        assert.file('protocol/hello.pb.gw.go')
        assert.file('protocol/hello.proto')
        assert.file('server/serve_test.go')
        assert.file('server/serve.go')
        assert.file('server/rpc.defs.go')
        assert.file('swagger/favicon-16x16.png')
        assert.file('swagger/favicon-32x32.png')
        assert.file('swagger/index.html')
        assert.file('swagger/oauth2-redirect.html')
        assert.file('swagger/protocol.swagger.json')
        assert.file('swagger/swagger-ui-bundle.js')
        assert.file('swagger/swagger-ui-bundle.js.map')
        assert.file('swagger/swagger-ui-standalone-preset.js')
        assert.file('swagger/swagger-ui-standalone-preset.js.map')
        assert.file('swagger/swagger-ui.css')
        assert.file('swagger/swagger-ui.css.map')
        assert.file('swagger/swagger-ui.js')
        assert.file('swagger/swagger-ui.js.map')
        assert.file('vendor/vendor.json')
        assert.file('.gitignore')
        assert.file('docker-test.sh')
        assert.file('version')
        assert.file('README.md')
        assert.fileContent('README.md', /# some-service/)
        assert.file('circle.yml')
        assert.file('Dockerfile')
        assert.file('main.go')
    })
})