// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hello/hello.proto

/*
Package hello is a generated protocol buffer package.

It is generated from these files:
	hello/hello.proto

It has these top-level messages:
	Empty
	HelloRequest
	HelloReply
	VersionResponse
*/
package protocol

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The request message containing the user's name.
type HelloRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *HelloRequest) Reset()                    { *m = HelloRequest{} }
func (m *HelloRequest) String() string            { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()               {}
func (*HelloRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HelloRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Message string `protobuf:"bytes,1,opt,name=message" json:"message,omitempty"`
}

func (m *HelloReply) Reset()                    { *m = HelloReply{} }
func (m *HelloReply) String() string            { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()               {}
func (*HelloReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HelloReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

// The response message contains the version
type VersionResponse struct {
	Version string `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
}

func (m *VersionResponse) Reset()                    { *m = VersionResponse{} }
func (m *VersionResponse) String() string            { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()               {}
func (*VersionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func init() {
	proto.RegisterType((*Empty)(nil), "hello.Empty")
	proto.RegisterType((*HelloRequest)(nil), "hello.HelloRequest")
	proto.RegisterType((*HelloReply)(nil), "hello.HelloReply")
	proto.RegisterType((*VersionResponse)(nil), "hello.VersionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Greeter service

type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
	Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := grpc.Invoke(ctx, "/hello.Greeter/SayHello", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *greeterClient) Version(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := grpc.Invoke(ctx, "/hello.Greeter/Version", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Greeter service

type GreeterServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	Version(context.Context, *Empty) (*VersionResponse, error)
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Greeter/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Greeter_Version_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GreeterServer).Version(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.Greeter/Version",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GreeterServer).Version(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _Greeter_SayHello_Handler,
		},
		{
			MethodName: "Version",
			Handler:    _Greeter_Version_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "hello/hello.proto",
}

func init() { proto.RegisterFile("hello/hello.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 256 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0xc1, 0x4a, 0xc4, 0x30,
	0x10, 0x86, 0xa9, 0xb8, 0x56, 0x87, 0x85, 0xb5, 0x23, 0x68, 0x29, 0x1e, 0x24, 0x07, 0x11, 0x84,
	0x2d, 0xea, 0x1b, 0x08, 0xe2, 0x1e, 0x3c, 0x55, 0xf0, 0xe0, 0x2d, 0xc2, 0x50, 0x0b, 0x69, 0x26,
	0x36, 0x71, 0x21, 0x57, 0x5f, 0xc1, 0x27, 0xf0, 0x99, 0x7c, 0x05, 0x1f, 0x44, 0x76, 0x9a, 0x82,
	0xee, 0x25, 0xe4, 0x1f, 0xbe, 0x4c, 0xfe, 0xff, 0x87, 0xe2, 0x95, 0x8c, 0xe1, 0x5a, 0xce, 0xa5,
	0x1b, 0x38, 0x30, 0xce, 0x44, 0x54, 0xa7, 0x2d, 0x73, 0x6b, 0xa8, 0xd6, 0xae, 0xab, 0xb5, 0xb5,
	0x1c, 0x74, 0xe8, 0xd8, 0xfa, 0x11, 0x52, 0x39, 0xcc, 0xee, 0x7a, 0x17, 0xa2, 0x52, 0x30, 0x5f,
	0x6d, 0xf8, 0x86, 0xde, 0xde, 0xc9, 0x07, 0x44, 0xd8, 0xb5, 0xba, 0xa7, 0x32, 0x3b, 0xcb, 0x2e,
	0x0e, 0x1a, 0xb9, 0xab, 0x73, 0x80, 0xc4, 0x38, 0x13, 0xb1, 0x84, 0xbc, 0x27, 0xef, 0x75, 0x3b,
	0x41, 0x93, 0x54, 0x97, 0xb0, 0x78, 0xa2, 0xc1, 0x77, 0x6c, 0x1b, 0xf2, 0x8e, 0xad, 0xa7, 0x0d,
	0xbc, 0x1e, 0x47, 0x13, 0x9c, 0xe4, 0xf5, 0x57, 0x06, 0xf9, 0xfd, 0x40, 0x14, 0x68, 0xc0, 0x07,
	0xd8, 0x7f, 0xd4, 0x51, 0xfe, 0xc0, 0xa3, 0xe5, 0x18, 0xe6, 0xaf, 0xab, 0xaa, 0xf8, 0x3f, 0x74,
	0x26, 0xaa, 0xf2, 0xe3, 0xfb, 0xe7, 0x73, 0x07, 0xf1, 0x50, 0x12, 0xae, 0xaf, 0x6a, 0xaf, 0xa3,
	0x40, 0xb8, 0x82, 0x3c, 0xd9, 0xc0, 0x79, 0x7a, 0x27, 0x59, 0xab, 0xe3, 0xa4, 0xb6, 0x4c, 0xaa,
	0x13, 0x59, 0x55, 0xe0, 0x62, 0x5a, 0x95, 0x3c, 0xde, 0xe6, 0xcf, 0x63, 0x99, 0x2f, 0x7b, 0xd2,
	0xda, 0xcd, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2a, 0x8e, 0xd1, 0xb3, 0x6f, 0x01, 0x00, 0x00,
}
